# -*- coding: utf-8 -*-
"""lab2_leonardo_Saenz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhO2N2qc3rIYOAfVccDr0544ZGSQUj7o
"""

import random
import math
import matplotlib.pyplot as plt


def generar_direcciones(n):
    direcciones = []
    for _ in range(n):
        punto = (random.randint(0, 10000), random.randint(0, 10000))
        direcciones.append(punto)
    return direcciones


class Nodo():
    def __init__(self, punto, derecha, izquierda, profundidad):
        self.punto = punto
        self.izquierda = izquierda
        self.derecha = derecha
        self.profundidad = profundidad


def construirArbol(direcciones, profundidad=0):
    if not direcciones:
        return None

    eje = profundidad % 2

    listaOrdenada = sorted(direcciones, key=lambda x: x[eje])
    indiceMedio = len(listaOrdenada) // 2
    valorMedio = listaOrdenada[indiceMedio]
    nodo = Nodo(valorMedio, None, None, profundidad)

    izquierda = listaOrdenada[:indiceMedio]
    derecha = listaOrdenada[indiceMedio+1:]

    nodo.izquierda = construirArbol(izquierda, profundidad+1)
    nodo.derecha = construirArbol(derecha, profundidad+1)

    return nodo

def calcularDistancia(punto1, punto2):
    distancia = math.sqrt((punto2[0] - punto1[0])**2 + (punto2[1] - punto1[1])**2)
    return distancia

def dentroDelRadio(punto1, punto2, radio):
    distanciaEntreDosPuntos = calcularDistancia(punto1, punto2)
    if distanciaEntreDosPuntos <= radio:
        return True
    else:
        return False

def rangeSearch(nodo, puntoComparar, radio, datosEncontrados=None):
    if datosEncontrados is None:
        datosEncontrados = []
    if nodo is None:
        return datosEncontrados

    dentro = dentroDelRadio(nodo.punto, puntoComparar, radio)
    if dentro == True:
        datosEncontrados.append(nodo.punto)

    eje = nodo.profundidad % 2
    distanciaEje = abs(puntoComparar[eje] - nodo.punto[eje])

    if puntoComparar[eje] <= nodo.punto[eje]:
        rangeSearch(nodo.izquierda, puntoComparar, radio, datosEncontrados)
        if distanciaEje <= radio:
            rangeSearch(nodo.derecha, puntoComparar, radio, datosEncontrados)
    else:
        rangeSearch(nodo.derecha, puntoComparar, radio, datosEncontrados)
        if distanciaEje <= radio:
            rangeSearch(nodo.izquierda, puntoComparar, radio, datosEncontrados)

    return datosEncontrados

def puntoMasCercano(nodo, punto):
    if nodo is None:
        return None
    mejorPunto = nodo.punto
    mejorDistancia = calcularDistancia(nodo.punto, punto)
    eje = nodo.profundidad % 2
    if punto[eje] < nodo.punto[eje]:
        caminoPrincipal = puntoMasCercano(nodo.izquierda, punto)
        caminoSecundario = nodo.derecha
    else:
        caminoPrincipal = puntoMasCercano(nodo.derecha, punto)
        caminoSecundario = nodo.izquierda
    if caminoPrincipal is not None:
        distancia = calcularDistancia(caminoPrincipal, punto)
        if distancia < mejorDistancia:
            mejorPunto = caminoPrincipal
            mejorDistancia = distancia
    distanciaPlano = abs(punto[eje] - nodo.punto[eje])
    if distanciaPlano < mejorDistancia:
        posible = puntoMasCercano(caminoSecundario, punto)
        if posible is not None:
            distancia = calcularDistancia(posible, punto)
            if distancia < mejorDistancia:
                mejorPunto = posible
    return mejorPunto


def puntoMasCercanoFuerzaBruta(direcciones, punto):
    mejorPunto = direcciones[0]
    mejorDistancia = calcularDistancia(direcciones[0], punto)
    for i in direcciones:
        distancia = calcularDistancia(i, punto)
        if distancia < mejorDistancia:
            mejorDistancia = distancia
            mejorPunto = i
    return mejorPunto


def visualizar_todo(direcciones, puntoBusqueda, radio, puntoCercano, resultadosRadio):
    fig, axes = plt.subplots(1, 2, figsize=(20, 10))


    xs = [p[0] for p in direcciones]
    ys = [p[1] for p in direcciones]

    ax1 = axes[0]
    ax1.set_title("Range Search — puntos dentro del radio (500m)")
    ax1.set_xlim(0, 10000)
    ax1.set_ylim(0, 10000)
    ax1.scatter(xs, ys, color='gray', s=5, zorder=3, label='puntos de entrega')
    if resultadosRadio:
        xr = [p[0] for p in resultadosRadio]
        yr = [p[1] for p in resultadosRadio]
        ax1.scatter(xr, yr, color='green', s=30, zorder=4,
                    label=f'dentro del radio ({len(resultadosRadio)})')
    circulo = plt.Circle(puntoBusqueda, radio, color='blue', fill=False,
                         linewidth=1.5, linestyle='--', zorder=5)
    ax1.add_patch(circulo)
    ax1.scatter(*puntoBusqueda, color='red', s=80, zorder=6, label='punto consulta')
    ax1.annotate(f"Q{puntoBusqueda}", puntoBusqueda,
                 textcoords="offset points", xytext=(8, 8), fontsize=8, color='red')
    ax1.legend()
    ax1.set_xlabel("X (metros)")
    ax1.set_ylabel("Y (metros)")
    ax1.grid(True, alpha=0.3)


    ax2 = axes[1]
    ax2.set_title("Vecino más cercano")
    ax2.set_xlim(0, 10000)
    ax2.set_ylim(0, 10000)
    ax2.scatter(xs, ys, color='gray', s=5, zorder=3, label='puntos de entrega')
    ax2.plot([puntoBusqueda[0], puntoCercano[0]],
             [puntoBusqueda[1], puntoCercano[1]],
             color='orange', linewidth=1.5, linestyle='--', zorder=4)
    mx = (puntoBusqueda[0] + puntoCercano[0]) / 2
    my = (puntoBusqueda[1] + puntoCercano[1]) / 2
    dist = calcularDistancia(puntoBusqueda, puntoCercano)
    ax2.annotate(f"d={dist:.1f}m", (mx, my),
                 textcoords="offset points", xytext=(5, 5), fontsize=9, color='orange')
    ax2.scatter(*puntoCercano, color='green', s=80, zorder=5, label='más cercano')
    ax2.annotate(f"{puntoCercano}", puntoCercano,
                 textcoords="offset points", xytext=(8, 8), fontsize=8, color='green')
    ax2.scatter(*puntoBusqueda, color='red', s=80, zorder=6, label='punto consulta')
    ax2.annotate(f"Q{puntoBusqueda}", puntoBusqueda,
                 textcoords="offset points", xytext=(8, 8), fontsize=8, color='red')
    ax2.legend()
    ax2.set_xlabel("X (metros)")
    ax2.set_ylabel("Y (metros)")
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()



puntoBusqueda = (7000, 5000)
radio = 500

random.seed(1)
direcciones = generar_direcciones(10000)
raiz = construirArbol(direcciones)

print(f"Distancia entre (1,2) y (3,5): {calcularDistancia((1, 2), (3, 5)):.2f} metros")
print(f"¿(1,2) está dentro del radio 5 de (3,5)?: {dentroDelRadio((1, 2), (3, 5), 5)}")
print(f"Punto raíz del árbol: {raiz.punto}")


resultados = rangeSearch(raiz, puntoBusqueda, radio)
print(f"Puntos dentro del radio: {resultados}")
print(f"Total puntos encontrados: {len(resultados)}")

puntoCercano = puntoMasCercano(raiz, puntoBusqueda)
puntoCercanoFuerzaBruta = puntoMasCercanoFuerzaBruta(direcciones, puntoBusqueda)
print(f"Punto más cercano (fuerza bruta): {puntoCercanoFuerzaBruta}")
print(f"Punto más cercano (KD-tree):      {puntoCercano}")


visualizar_todo(direcciones, puntoBusqueda, radio, puntoCercano, resultados)

import time


inicio = time.perf_counter()
puntoMasCercano(raiz, puntoBusqueda)
tiempoKd = time.perf_counter() - inicio

print(f"KD-tree: {tiempoKd:.6f} segundos")