# -*- coding: utf-8 -*-
"""lab2_leonardo_Saenz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhO2N2qc3rIYOAfVccDr0544ZGSQUj7o
"""

import random
import math
import matplotlib.pyplot as plt


def generar_direcciones(n):
    direcciones = []
    for _ in range(n):
        punto = (random.randint(0, 10000), random.randint(0, 10000))
        direcciones.append(punto)
    return direcciones


class Nodo():
    def __init__(self, punto, derecha, izquierda, profundidad):
        self.punto = punto
        self.izquierda = izquierda
        self.derecha = derecha
        self.profundidad = profundidad


def construirArbol(direcciones, profundidad=0):
    if not direcciones:
        return None

    eje = profundidad % 2

    listaOrdenada = sorted(direcciones, key=lambda x: x[eje])
    indiceMedio = len(listaOrdenada) // 2
    valorMedio = listaOrdenada[indiceMedio]
    nodo = Nodo(valorMedio, None, None, profundidad)

    izquierda = listaOrdenada[:indiceMedio]
    derecha = listaOrdenada[indiceMedio+1:]

    nodo.izquierda = construirArbol(izquierda, profundidad+1)
    nodo.derecha = construirArbol(derecha, profundidad+1)

    return nodo

def calcularDistancia(punto1, punto2):
    distancia = math.sqrt((punto2[0] - punto1[0])**2 + (punto2[1] - punto1[1])**2)
    return distancia

def dentroDelRadio(punto1, punto2, radio):
    distanciaEntreDosPuntos = calcularDistancia(punto1, punto2)
    if distanciaEntreDosPuntos <= radio:
        return True
    else:
        return False

def rangeSearch(nodo, puntoComparar, radio, datosEncontrados=None):
    if datosEncontrados is None:
        datosEncontrados = []
    if nodo is None:
        return datosEncontrados

    dentro = dentroDelRadio(nodo.punto, puntoComparar, radio)
    if dentro == True:
        datosEncontrados.append(nodo.punto)

    eje = nodo.profundidad % 2
    distanciaEje = abs(puntoComparar[eje] - nodo.punto[eje])

    if puntoComparar[eje] <= nodo.punto[eje]:
        rangeSearch(nodo.izquierda, puntoComparar, radio, datosEncontrados)
        if distanciaEje <= radio:
            rangeSearch(nodo.derecha, puntoComparar, radio, datosEncontrados)
    else:
        rangeSearch(nodo.derecha, puntoComparar, radio, datosEncontrados)
        if distanciaEje <= radio:
            rangeSearch(nodo.izquierda, puntoComparar, radio, datosEncontrados)

    return datosEncontrados

def puntoMasCercano(nodo, punto):
    if nodo is None:
        return None
    mejorPunto = nodo.punto
    mejorDistancia = calcularDistancia(nodo.punto, punto)
    eje = nodo.profundidad % 2
    if punto[eje] < nodo.punto[eje]:
        caminoPrincipal = puntoMasCercano(nodo.izquierda, punto)
        caminoSecundario = nodo.derecha
    else:
        caminoPrincipal = puntoMasCercano(nodo.derecha, punto)
        caminoSecundario = nodo.izquierda
    if caminoPrincipal is not None:
        distancia = calcularDistancia(caminoPrincipal, punto)
        if distancia < mejorDistancia:
            mejorPunto = caminoPrincipal
            mejorDistancia = distancia
    distanciaPlano = abs(punto[eje] - nodo.punto[eje])
    if distanciaPlano < mejorDistancia:
        posible = puntoMasCercano(caminoSecundario, punto)
        if posible is not None:
            distancia = calcularDistancia(posible, punto)
            if distancia < mejorDistancia:
                mejorPunto = posible
    return mejorPunto


def puntoMasCercanoFuerzaBruta(direcciones, punto):
    mejorPunto = direcciones[0]
    mejorDistancia = calcularDistancia(direcciones[0], punto)
    for i in direcciones:
        distancia = calcularDistancia(i, punto)
        if distancia < mejorDistancia:
            mejorDistancia = distancia
            mejorPunto = i
    return mejorPunto


def visualizar_todo(direcciones, puntoBusqueda, radio, puntoCercano, resultadosRadio):
    fig, axes = plt.subplots(1, 2, figsize=(20, 10))

    xs = [p[0] for p in direcciones]
    ys = [p[1] for p in direcciones]


    ax1 = axes[0]
    ax1.set_title("Range Search — puntos dentro del radio (500m)")
    ax1.set_xlim(0, 10000)
    ax1.set_ylim(0, 10000)
    ax1.scatter(xs, ys, color='gray', s=5, zorder=3, label='puntos de entrega')
    if resultadosRadio:
        xr = [p[0] for p in resultadosRadio]
        yr = [p[1] for p in resultadosRadio]
        ax1.scatter(xr, yr, color='green', s=30, zorder=4,
                    label=f'dentro del radio ({len(resultadosRadio)})')
    circulo = plt.Circle(puntoBusqueda, radio, color='blue', fill=False,
                         linewidth=1.5, linestyle='--', zorder=5)
    ax1.add_patch(circulo)
    ax1.scatter(*puntoBusqueda, color='red', s=80, zorder=6, label='punto consulta')
    ax1.annotate(f"Q{puntoBusqueda}", puntoBusqueda,
                 textcoords="offset points", xytext=(8, 8), fontsize=8, color='red')
    ax1.legend()
    ax1.set_xlabel("X (metros)")
    ax1.set_ylabel("Y (metros)")
    ax1.grid(True, alpha=0.3)


    ax2 = axes[1]
    dist = calcularDistancia(puntoBusqueda, puntoCercano)
    margen = max(dist * 5, 300)

    x_min = max(0,     min(puntoBusqueda[0], puntoCercano[0]) - margen)
    x_max = min(10000, max(puntoBusqueda[0], puntoCercano[0]) + margen)
    y_min = max(0,     min(puntoBusqueda[1], puntoCercano[1]) - margen)
    y_max = min(10000, max(puntoBusqueda[1], puntoCercano[1]) + margen)


    puntos_zoom = [(x, y) for x, y in direcciones
                   if x_min <= x <= x_max and y_min <= y <= y_max]
    xz = [p[0] for p in puntos_zoom]
    yz = [p[1] for p in puntos_zoom]

    ax2.set_title(f"Vecino más cercano (zoom  ·  d = {dist:.1f} m)")
    ax2.set_xlim(x_min, x_max)
    ax2.set_ylim(y_min, y_max)
    ax2.scatter(xz, yz, color='gray', s=15, zorder=3, label='puntos de entrega')

    ax2.plot([puntoBusqueda[0], puntoCercano[0]],
             [puntoBusqueda[1], puntoCercano[1]],
             color='orange', linewidth=2, linestyle='--', zorder=4)

    mx = (puntoBusqueda[0] + puntoCercano[0]) / 2
    my = (puntoBusqueda[1] + puntoCercano[1]) / 2
    ax2.annotate(f"d={dist:.1f}m", (mx, my),
                 textcoords="offset points", xytext=(5, 5), fontsize=10, color='orange')

    ax2.scatter(*puntoCercano, color='green', s=120, zorder=5, label='más cercano')
    ax2.annotate(f"{puntoCercano}", puntoCercano,
                 textcoords="offset points", xytext=(8, 8), fontsize=9, color='green')

    ax2.scatter(*puntoBusqueda, color='red', s=120, zorder=6, label='punto consulta')
    ax2.annotate(f"Q{puntoBusqueda}", puntoBusqueda,
                 textcoords="offset points", xytext=(8, -15), fontsize=9, color='red')

    ax2.legend()
    ax2.set_xlabel("X (metros)")
    ax2.set_ylabel("Y (metros)")
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()



puntoBusqueda = (7000, 5000)
radio = 500

random.seed(8)
direcciones = generar_direcciones(10000)
raiz = construirArbol(direcciones)

print(f"Distancia entre (1,2) y (3,5): {calcularDistancia((1, 2), (3, 5)):.2f} metros")
print(f"¿(1,2) está dentro del radio 5 de (3,5)?: {dentroDelRadio((1, 2), (3, 5), 5)}")
print(f"Punto raíz del árbol: {raiz.punto}")


resultados = rangeSearch(raiz, puntoBusqueda, radio)
print(f"Puntos dentro del radio: {resultados}")
print(f"Total puntos encontrados: {len(resultados)}")

puntoCercano = puntoMasCercano(raiz, puntoBusqueda)
puntoCercanoFuerzaBruta = puntoMasCercanoFuerzaBruta(direcciones, puntoBusqueda)
print(f"Punto más cercano (fuerza bruta): {puntoCercanoFuerzaBruta}")
print(f"Punto más cercano (KD-tree):      {puntoCercano}")


visualizar_todo(direcciones, puntoBusqueda, radio, puntoCercano, resultados)

import time

def rangeSearchFuerzaBruta(direcciones, punto, radio):
    resultado = []
    for p in direcciones:
        if dentroDelRadio(p, punto, radio):
            resultado.append(p)
    return resultado

# tamaños a probar
tamanios = [10, 100, 1000, 5000, 10000]

tiempos_fb_cercano = []
tiempos_kd_cercano = []
tiempos_fb_radio   = []
tiempos_kd_radio   = []

print("--- Vecino más cercano ---")
print("n        | Fuerza bruta (s) | KD-tree (s)")
print("-" * 45)

for n in tamanios:
    datos = direcciones[:n]
    arbol = construirArbol(datos)

    inicio = time.perf_counter()
    puntoMasCercanoFuerzaBruta(datos, puntoBusqueda)
    tiempos_fb_cercano.append(time.perf_counter() - inicio)

    inicio = time.perf_counter()
    puntoMasCercano(arbol, puntoBusqueda)
    tiempos_kd_cercano.append(time.perf_counter() - inicio)

    print(f"n={n:6d} | {tiempos_fb_cercano[-1]:.6f}s        | {tiempos_kd_cercano[-1]:.6f}s")

print("\n--- Range Search ---")
print("n        | Fuerza bruta (s) | KD-tree (s)")
print("-" * 45)

for n in tamanios:
    datos = direcciones[:n]
    arbol = construirArbol(datos)

    inicio = time.perf_counter()
    rangeSearchFuerzaBruta(datos, puntoBusqueda, radio)
    tiempos_fb_radio.append(time.perf_counter() - inicio)

    inicio = time.perf_counter()
    rangeSearch(arbol, puntoBusqueda, radio)
    tiempos_kd_radio.append(time.perf_counter() - inicio)

    print(f"n={n:6d} | {tiempos_fb_radio[-1]:.6f}s        | {tiempos_kd_radio[-1]:.6f}s")

# graficas lado a lado
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

axes[0].plot(tamanios, tiempos_fb_cercano, 'r-o', label='Fuerza bruta')
axes[0].plot(tamanios, tiempos_kd_cercano, 'b-o', label='KD-tree')
axes[0].set_title("Vecino más cercano")
axes[0].set_xlabel("Número de puntos (n)")
axes[0].set_ylabel("Tiempo (segundos)")
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(tamanios, tiempos_fb_radio, 'r-o', label='Fuerza bruta')
axes[1].plot(tamanios, tiempos_kd_radio, 'b-o', label='KD-tree')
axes[1].set_title("Range Search")
axes[1].set_xlabel("Número de puntos (n)")
axes[1].set_ylabel("Tiempo (segundos)")
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()