# -*- coding: utf-8 -*-
"""Pruebas_Tiempo_Y_Analisis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6vY5l66h_L2kaEUOatjT1YLeWXv1BgW
"""

import random
import math
import matplotlib.pyplot as plt


#Abajo estan las pruebas de tiempo y analisis

def generar_direcciones(n):
    direcciones = []
    for _ in range(n):
        punto = (random.randint(0, 10000), random.randint(0, 10000))
        direcciones.append(punto)
    return direcciones


class Nodo():
    def __init__(self, punto, derecha, izquierda, profundidad):
        self.punto = punto
        self.izquierda = izquierda
        self.derecha = derecha
        self.profundidad = profundidad


def construirArbol(direcciones, profundidad=0):
    if not direcciones:
        return None

    eje = profundidad % 2

    listaOrdenada = sorted(direcciones, key=lambda x: x[eje])
    indiceMedio = len(listaOrdenada) // 2
    valorMedio = listaOrdenada[indiceMedio]
    nodo = Nodo(valorMedio, None, None, profundidad)

    izquierda = listaOrdenada[:indiceMedio]
    derecha = listaOrdenada[indiceMedio+1:]

    nodo.izquierda = construirArbol(izquierda, profundidad+1)
    nodo.derecha = construirArbol(derecha, profundidad+1)

    return nodo

def calcularDistancia(punto1, punto2):
    distancia = math.sqrt((punto2[0] - punto1[0])**2 + (punto2[1] - punto1[1])**2)
    return distancia

def dentroDelRadio(punto1, punto2, radio):
    distanciaEntreDosPuntos = calcularDistancia(punto1, punto2)
    if distanciaEntreDosPuntos <= radio:
        return True
    else:
        return False

def rangeSearch(nodo, puntoComparar, radio, datosEncontrados=None):
    if datosEncontrados is None:
        datosEncontrados = []
    if nodo is None:
        return datosEncontrados

    dentro = dentroDelRadio(nodo.punto, puntoComparar, radio)
    if dentro == True:
        datosEncontrados.append(nodo.punto)

    eje = nodo.profundidad % 2
    distanciaEje = abs(puntoComparar[eje] - nodo.punto[eje])

    if puntoComparar[eje] <= nodo.punto[eje]:
        rangeSearch(nodo.izquierda, puntoComparar, radio, datosEncontrados)
        if distanciaEje <= radio:
            rangeSearch(nodo.derecha, puntoComparar, radio, datosEncontrados)
    else:
        rangeSearch(nodo.derecha, puntoComparar, radio, datosEncontrados)
        if distanciaEje <= radio:
            rangeSearch(nodo.izquierda, puntoComparar, radio, datosEncontrados)

    return datosEncontrados

def puntoMasCercano(nodo, punto):
    if nodo is None:
        return None
    mejorPunto = nodo.punto
    mejorDistancia = calcularDistancia(nodo.punto, punto)
    eje = nodo.profundidad % 2
    if punto[eje] < nodo.punto[eje]:
        caminoPrincipal = puntoMasCercano(nodo.izquierda, punto)
        caminoSecundario = nodo.derecha
    else:
        caminoPrincipal = puntoMasCercano(nodo.derecha, punto)
        caminoSecundario = nodo.izquierda
    if caminoPrincipal is not None:
        distancia = calcularDistancia(caminoPrincipal, punto)
        if distancia < mejorDistancia:
            mejorPunto = caminoPrincipal
            mejorDistancia = distancia
    distanciaPlano = abs(punto[eje] - nodo.punto[eje])
    if distanciaPlano < mejorDistancia:
        posible = puntoMasCercano(caminoSecundario, punto)
        if posible is not None:
            distancia = calcularDistancia(posible, punto)
            if distancia < mejorDistancia:
                mejorPunto = posible
    return mejorPunto


def puntoMasCercanoFuerzaBruta(direcciones, punto):
    mejorPunto = direcciones[0]
    mejorDistancia = calcularDistancia(direcciones[0], punto)
    for i in direcciones:
        distancia = calcularDistancia(i, punto)
        if distancia < mejorDistancia:
            mejorDistancia = distancia
            mejorPunto = i
    return mejorPunto
def radioFuerzaBruta(direcciones, punto, radio):
    resultado = []
    for datos in direcciones:
        if dentroDelRadio(datos, punto, radio):
            resultado.append(datos)
    return resultado






puntoBusqueda = (7000, 5000)
radio = 500

random.seed(1)
direcciones = generar_direcciones(10000)
raiz = construirArbol(direcciones)

print(f"Distancia entre (1,2) y (3,5): {calcularDistancia((1, 2), (3, 5)):.2f} metros")
print(f"¿(1,2) está dentro del radio 5 de (3,5)?: {dentroDelRadio((1, 2), (3, 5), 5)}")
print(f"Punto raíz del árbol: {raiz.punto}")

resultado = radioFuerzaBruta(direcciones, puntoBusqueda, radio)
resultados = rangeSearch(raiz, puntoBusqueda, radio)
print(f"Puntos dentro del radio: {resultados}")
print(f"Total puntos encontrados (KD-TREE): {len(resultados)}")
print(f"Puntos encontrados del radio (fuerza bruta) {len(resultado)}")

puntoCercano = puntoMasCercano(raiz, puntoBusqueda)
puntoCercanoFuerzaBruta = puntoMasCercanoFuerzaBruta(direcciones, puntoBusqueda)
print(f"Punto más cercano (fuerza bruta): {puntoCercanoFuerzaBruta}")
print(f"Punto más cercano (KD-tree):      {puntoCercano}")

import time

def rangeSearchFuerzaBruta(direcciones, punto, radio):
    resultado = []
    for p in direcciones:
        if dentroDelRadio(p, punto, radio):
            resultado.append(p)
    return resultado

# tamaños a probar
tamaños = [10, 100, 1000, 5000, 10000]

tiempos_fb_cercano = []
tiempos_kd_cercano = []
tiempos_fb_radio   = []
tiempos_kd_radio   = []

print("--- Vecino más cercano ---")
print("n        | Fuerza bruta (s) | KD-tree (s)")
print("-" * 45)

for n in tamaños:
    datos = direcciones[:n]
    arbol = construirArbol(datos)

    inicio = time.perf_counter()
    puntoMasCercanoFuerzaBruta(datos, puntoBusqueda)
    tiempos_fb_cercano.append(time.perf_counter() - inicio)

    inicio = time.perf_counter()
    puntoMasCercano(arbol, puntoBusqueda)
    tiempos_kd_cercano.append(time.perf_counter() - inicio)

    print(f"n={n:6d} | {tiempos_fb_cercano[-1]:.6f}s        | {tiempos_kd_cercano[-1]:.6f}s")

print("\n--- Range Search ---")
print("n        | Fuerza bruta (s) | KD-tree (s)")
print("-" * 45)

for n in tamaños:
    datos = direcciones[:n]
    arbol = construirArbol(datos)

    inicio = time.perf_counter()
    rangeSearchFuerzaBruta(datos, puntoBusqueda, radio)
    tiempos_fb_radio.append(time.perf_counter() - inicio)

    inicio = time.perf_counter()
    rangeSearch(arbol, puntoBusqueda, radio)
    tiempos_kd_radio.append(time.perf_counter() - inicio)

    print(f"n={n:6d} | {tiempos_fb_radio[-1]:.6f}s        | {tiempos_kd_radio[-1]:.6f}s")

# graficas lado a lado
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

axes[0].plot(tamaños, tiempos_fb_cercano, 'r-o', label='Fuerza bruta')
axes[0].plot(tamaños, tiempos_kd_cercano, 'b-o', label='KD-tree')
axes[0].set_title("Vecino más cercano")
axes[0].set_xlabel("Número de puntos (n)")
axes[0].set_ylabel("Tiempo (segundos)")
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(tamaños, tiempos_fb_radio, 'r-o', label='Fuerza bruta')
axes[1].plot(tamaños, tiempos_kd_radio, 'b-o', label='KD-tree')
axes[1].set_title("Range Search")
axes[1].set_xlabel("Número de puntos (n)")
axes[1].set_ylabel("Tiempo (segundos)")
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""<center><h2> <b>Recopilacion de datos y analisis</b></center>

<b>Punto mas cercano<br></b>
<br>
Se hizo la recopilacion de datos y se saco el promedio de estos para poder analizar de mejor manera el rendimiento de cada uno de los algoritmos.

$n = 10      |	Fuerza bruta = 0.000015 s| 	KDtree = 0.00001325 s$<br><br>
$n = 100     | 	Fuerza bruta = 0.000035 s | 	KDtree = 0.000015 s$<br><br>
$n = 1000    | 	Fuerza bruta = 0.0003 s  | 	KDtree = 0.000024 s$<br><br>
$n = 5000    | 	Fuerza bruta = 0.0013 s | 	KDtree = 0.000042 s$<br><br>
$n = 10000   |	 Fuerza bruta = 0.0022 s  | 	KDtree = 0.000034 s$<br><br>


En cada uno de los índices n se van a obtener 4 datos de tiempo para fuerza bruta y 4 datos de tiempo para KD-tree, los cuales se promedian para obtener un valor más representativo del rendimiento de cada algoritmo.


<br> <b><h2>
<center>Punto más cercano  $ \frac{(Fuerza bruta)} {KDtree}$<br><br></center></b></h2>

$n = 10\quad|   \quad    \frac{(0.000015  )} {0.000013}= 1.1$ Veces más rápido el KD-tree que la fuerza bruta.<br><br>
$n = 100\quad|   \quad  \frac{(0.000035  )} {0.000015}  = 2$ Veces más rápido el KD-tree que la fuerza bruta.<br><br>
$n = 1000 \quad| \quad   \frac{(0.00030   )} {0.000024} = 12$ Veces más rápido el KD-tree que la fuerza bruta.<br><br>
$n = 5000   \quad | \quad \frac{(0.0013  )} {0.000042} = 31$ Veces más rápido el KD-tree que la fuerza bruta.<br><br>
$n = 10000  \quad | \quad \frac{(0.0022   )} {0.000034}= 64$ Veces más rápido el KD-tree que la fuerza bruta.
</center>

Ya con estos promedios vamos a compararlos con los del KD-TREE para ver que tan rápido es un método respecto a otro, y como queremos saber que tan rápido es el KD-tree respecto a la fuerza bruta vamos a usar la división de manera que ponemos <br>
<center>
$\frac{(FUERZA BRUTA   )} {KD-TREE}$
</center>
<br>
Ya hechas las operaciones, podemos analizar y concluir que la diferencia de los algoritmos cuando $“n = 10”$ , es mínima tanto que se podría decir que son igual de veloces a la hora de resolver el mismo problema.<br>
<br>
Ya con $“n=100”$ se ve la efectividad del algoritmo KD-TREE siendo este 2 veces mas rápido que la fuerza bruta teniendo un rendimiento considerablemente mejor, pero aún algo corto para lo que se esperaría.
<br>
<br>
La diferencia real se da cuando los datos escalan mucho más, en $“n =1000 “$ hacia arriba, la rapidez del KD-tree comparada al de la fuerza bruta escala de sobremanera, notándose mucho la diferencia en el tiempo de ejecución de estos dos algoritmos, dada la cantidad de datos que hay que revisar, el algoritmo de fuerza bruta solo le queda iterar en la lista de puntos hasta encontrar el que está mas cerca del punto a encontrar sin ninguna lógica adicional.
<Br><br>
En cambio el KD-tree al tener los puntos organizados y las divisiones por ejes puede reducir de gran manera las comparaciones necesarias recorriendo menos nodos, haciendo menos operaciones y siendo mucho más rápido, esto casi no se nota cuando $“n”$ tiene un valor bajo debido a que el árbol es muy pequeño y las secciones que corta no son tan grandes, pero en un árbol con $“n = 1000”$ se empieza a notar mucho la superioridad del KD-tree.

<br>
<br><h1><center><b>
RangeSearch  $ \frac{(Fuerza bruta)} {KDtree}$</b>
<Br></h1>
<br>
$n = 10     \quad |\quad \quad \frac{(0.000011   )} {0.0000062}= 1.7$ Veces más rápido el KD-tree que la fuerza bruta.<br><br>
$n = 100    \quad |\quad \quad\frac{( 0.000027   )} {0.0000052} = 5$ Veces más rápido el KD-tree que la fuerza bruta.<br><br>
$n = 1000   \quad |\quad \quad \frac{( 0.00026   )} {0.000024}
 = 10$ Veces más rápido el KD-tree que la fuerza bruta.<br><br>
$n = 5000   \quad |\quad \quad \frac{( 0.0013  )} { 0.000079}= 17$	 Veces más rápido el KD-tree que la fuerza bruta.<br><br>
$n = 10000 \quad | \quad\quad\frac{(0.0027 )} { 0.00013}  = 20$ Veces más rápido el KD-tree que la fuerza bruta.<br><br>


Se hace el mismo procedimiento se pone $\frac{(Fuerza bruta )} { KDTree}$ para así ver que tan rápido es un algoritmo respecto a otro.<br><br>
De la misma manera cuando $“n”$ tiene un valor bajo como $10$ los dos algoritmos van mas o menos parecidos, siendo el KD-tree un poco más rápido pero no siendo algo muy destacable.<br><br>
Ya desde $n = 100$ se puede ver una gran diferencia, siendo el KD-tree alrededor de $5$ veces más rápido que la fuerza bruta. Este aumento se vuelve cada vez más notable conforme crece la cantidad de datos. Esto se debe a que la búsqueda en rango es un proceso en el que se debe revisar cuáles puntos se encuentran dentro de una distancia determinada con respecto al punto de búsqueda.
<br>
<br>
<center> <b><h1>Analisis final y conclusiones</b> </center>
<br>

El KDTree es un algoritmo que en búsquedas grandes es tremendamente eficiente, pero que en búsquedas pequeñas no marca mucho la diferencia con otros algoritmos más simples o llamados de "fuerza bruta". Mientras que los algoritmos de fuerza bruta son fáciles de implementar y eficientes en datos chicos, no tienen gran escalabilidad, cosa que el KD-tree sí tiene.

<br>
<br>
Otra cosa importante es que el KD-tree escala mejor en la búsqueda de un solo dato que en la búsqueda por rango. Aunque el Range Search al principio muestra una mejora notable, llegando en $n = 100$ a ser $5$ veces más rápido que la fuerza bruta, su ventaja no aumenta tanto como en la búsqueda del punto más cercano. Esto ocurre porque, en datos pequeños, el árbol puede descartar rápidamente muchas regiones y concentrarse solo en unas pocas, haciendo más eficiente la búsqueda. Sin embargo, conforme aumenta el tamaño de la entrada, la búsqueda por rango sigue necesitando revisar todas las zonas que puedan contener puntos dentro del radio, mientras que en la búsqueda del punto más cercano el KD-tree puede descartar más ramas y reducir mucho más el número de comparaciones.
<br>
<br>
El KD-tree es una gran herramienta ideal para grandes proyectos, puede llegar a verse algo intimidante, pero entenderlo vale la pena si en un proyecto se quieren manejar grandes volúmenes de datos, si no es necesario, lo mejor sería usar una algoritmo de fuerza bruta, ya que estos son casi igual de eficientes con pocos datos.





"""

