# -*- coding: utf-8 -*-
"""Analisis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7o9gJbO3pwqYwQI_rL1AMlwoRHYFnqK

En el siguiente analisis se pretende hacer una comparacion de la busqueda de el dato mas cercano de un Quadtree vs un algoritmo de fuerza bruta.

<br>
la recoleccion de datos nos da lo siguiente

<b>Punto mas cercano<br></b>
<br>
Se hizo la recopilacion de datos para poder analizar de mejor manera el rendimiento de cada uno de los algoritmos.

$n = 100      |	Fuerza bruta = 0.000046 s| 	Quadtree = 0.000007 s$<br><br>
$n = 500     | 	Fuerza bruta = 0.00018 s | 	Quadtree = 0.000008 s$<br><br>
$n = 1000    | 	Fuerza bruta = 0.00053 s  | 	Quadtree = 0.000012 s$<br><br>
$n = 5000    | 	Fuerza bruta = 0.0018s | 	Quadtree = 0.000015 s$<br><br>
$n = 10000   |	 Fuerza bruta = 0.0037 s  | 	Quadtree = 0.000021 s$<br><br>

<br>
$n = 100\quad|   \quad    \frac{(0.000046  )} {0.000007}= 6$ Veces más rápido el Quadtree que la fuerza bruta.<br><br>
$n = 500\quad|   \quad  \frac{(0.00018  )} {0.000008}  = 22$ Veces más rápido el Quadtree que la fuerza bruta.<br><br>
$n = 1000 \quad| \quad   \frac{(0.00053   )} {0.000012} = 44$ Veces más rápido el Quadtree que la fuerza bruta.<br><br>
$n = 5000   \quad | \quad \frac{(0.0018  )} {0.000015} = 120$ Veces más rápido el Quadtree que la fuerza bruta.<br><br>
$n = 10000  \quad | \quad \frac{(0.0037   )} {0.000021}= 176$ Veces más rápido el Quadtree que la fuerza bruta.
</center>


<br>
<br>
Aunque la implementación presenta algunas falencias, los datos obtenidos en las pruebas muestran que el Quadtree tuvo tiempos de búsqueda considerablemente menores que la fuerza bruta. Esto sugiere que la partición espacial del plano hizo que estos tiempos bajaran e incluso casi que se mantuvieran constantes en sus tiempos de búsqueda, al contrario de la fuerza bruta, que entre más datos se le suministraban este empeoraba de manera clara. Y aunque cuando "n" pasó de 500 a 1000 el Quadtree lanzó tiempos 10 veces peores que en valores de "n" menores, este, en comparación con la fuerza bruta, siguió siendo superior, incluso marcando más la diferencia.
"""

