# -*- coding: utf-8 -*-
"""quadtree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5xRx2Vvs4wJQMuXytwRKlwzcfvZerXZ
"""

import random
import math
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import time

def generar_direcciones(n):
    direcciones = []
    for _ in range(n):
        punto = (random.randint(0, 10000), random.randint(0, 10000))
        direcciones.append(punto)
    return direcciones

class Nodo():
    def __init__(self, xMin, xMax, yMin, yMax):
        self.xMin = xMin
        self.xMax = xMax
        self.yMin = yMin
        self.yMax = yMax
        self.puntos = []
        self.hijos = []
        self.esHoja = True

def crearArbol(nodo, direcciones ):


    nodo.puntos = []
    for i in direcciones:
        x = i[0]
        y = i[1]
        dentroEnX = nodo.xMin <= x <= nodo.xMax
        dentroEnY = nodo.yMin <= y <= nodo.yMax
        if dentroEnX and dentroEnY:
            nodo.puntos.append(i)

    #Caso base
    if len(nodo.puntos) <= 1:
        return


    medioX = (nodo.xMin + nodo.xMax) / 2
    medioY = (nodo.yMin + nodo.yMax) / 2

    nodo.esHoja = False
    nodo.hijos = [
        Nodo(nodo.xMin,medioX,medioY,nodo.yMax),
        Nodo(medioX,nodo.xMax, medioY,nodo.yMax),
        Nodo(nodo.xMin,medioX,nodo.yMin, medioY),
        Nodo(medioX,nodo.xMax,nodo.yMin,medioY),
    ]

    for hijo in nodo.hijos:
      crearArbol(hijo, nodo.puntos)

def calcularDistancia (punto1, punto2):
  return math.sqrt((punto1[0] - punto2[0])**2 + (punto1[1] - punto2[1])**2)
def buscarVecino(nodo, puntoBuscar):
    if nodo.esHoja:
        if len(nodo.puntos) == 0:
            return None
        candidato = nodo.puntos[0]
        mejorDistancia = calcularDistancia(puntoBuscar, candidato)
        for punto in nodo.puntos:
            dista = calcularDistancia(puntoBuscar, punto)
            if dista < mejorDistancia:
                mejorDistancia = dista
                candidato = punto
        return candidato

    medioX = (nodo.xMin + nodo.xMax) / 2
    medioY = (nodo.yMin + nodo.yMax) / 2
    x = puntoBuscar[0]
    y = puntoBuscar[1]

    if x < medioX and y >= medioY:
        return buscarVecino(nodo.hijos[0], puntoBuscar)
    if x >= medioX and y >= medioY:
        return buscarVecino(nodo.hijos[1], puntoBuscar)
    if x < medioX and y < medioY:
        return buscarVecino(nodo.hijos[2], puntoBuscar)
    if x >= medioX and y < medioY:
        return buscarVecino(nodo.hijos[3], puntoBuscar)




def puntoMasCercanoFuerzaBruta(direcciones, punto):
    mejorPunto = direcciones[0]
    mejorDistancia = calcularDistancia(direcciones[0], punto)

    for i in direcciones:
        dista = calcularDistancia(i, punto)
        if dista < mejorDistancia:
            mejorDistancia = dista
            mejorPunto = i

    return mejorPunto




def dibujar(nodo, ax):
    if nodo.esHoja:
        rect = patches.Rectangle(
            (nodo.xMin, nodo.yMin),
            nodo.xMax - nodo.xMin,
            nodo.yMax - nodo.yMin,
            linewidth=0.5,
            edgecolor='steelblue',
            facecolor='lightyellow'
        )
        ax.add_patch(rect)
        for p in nodo.puntos:
            ax.plot(p[0], p[1], 'o', color='tomato', markersize=3)
    else:
        for hijo in nodo.hijos:
            dibujar(hijo, ax)
random.seed(15)

direcciones = generar_direcciones(10000)
raiz = Nodo(0, 10000, 0, 10000)
crearArbol(raiz, direcciones)
puntoBuscar =(4500,3200)
inicio = time.time()
fuerzaBrutabusqueda = puntoMasCercanoFuerzaBruta(direcciones, puntoBuscar)
fin = time.time()
tiempoBruta = fin -inicio
inicio = time.time()
buscarV = buscarVecino(raiz, puntoBuscar)
fin = time.time()
tiempoArbol = fin - inicio
print("Vecino más cercano  arbol:", buscarV)
print("Vecino más cercano fuerza bruta:", fuerzaBrutabusqueda)
print(f"Tiempo quadtree:     {tiempoArbol:.6f} segundos")
print(f"Tiempo fuerza bruta: {tiempoBruta:.6f} segundos")
fig, ax = plt.subplots(figsize=(8, 8))
dibujar(raiz, ax)
ax.set_xlim(0, 10000)
ax.set_ylim(0, 10000)
ax.set_title("Quadtree")
ax.set_aspect('equal')
plt.tight_layout()
plt.show()