# -*- coding: utf-8 -*-
"""quadtree_tiempos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17qPqqY9fZEg2qEIpqOVlS2krhj4PMg2h
"""

import random
import math
import matplotlib.pyplot as plt
import time

def generar_direcciones(n):
    direcciones = []
    for _ in range(n):
        punto = (random.randint(0, 10000), random.randint(0, 10000))
        direcciones.append(punto)
    return direcciones

class Nodo():
    def __init__(self, xMin, xMax, yMin, yMax):
        self.xMin = xMin
        self.xMax = xMax
        self.yMin = yMin
        self.yMax = yMax
        self.puntos = []
        self.hijos = []
        self.esHoja = True

def crearArbol(nodo, direcciones):
    nodo.puntos = []
    for i in direcciones:
        x = i[0]
        y = i[1]
        dentroEnX = nodo.xMin <= x <= nodo.xMax
        dentroEnY = nodo.yMin <= y <= nodo.yMax
        if dentroEnX and dentroEnY:
            nodo.puntos.append(i)

    # caso base
    if len(nodo.puntos) <= 4:
        return

    medioX = (nodo.xMin + nodo.xMax) / 2
    medioY = (nodo.yMin + nodo.yMax) / 2

    nodo.esHoja = False
    nodo.hijos = [
        Nodo(nodo.xMin, medioX, medioY, nodo.yMax),
        Nodo(medioX, nodo.xMax, medioY, nodo.yMax),
        Nodo(nodo.xMin, medioX, nodo.yMin, medioY),
        Nodo(medioX, nodo.xMax, nodo.yMin, medioY),
    ]

    for hijo in nodo.hijos:
        crearArbol(hijo, nodo.puntos)

def calcularDistancia(punto1, punto2):
    return math.sqrt((punto1[0] - punto2[0])**2 + (punto1[1] - punto2[1])**2)

def buscarVecino(nodo, puntoBuscar):
    if nodo.esHoja:
        if len(nodo.puntos) == 0:
            return None

        candidato = nodo.puntos[0]
        mejorDistancia = calcularDistancia(puntoBuscar, candidato)

        for punto in nodo.puntos:
            dista = calcularDistancia(puntoBuscar, punto)
            if dista < mejorDistancia:
                mejorDistancia = dista
                candidato = punto
        return candidato

    medioX = (nodo.xMin + nodo.xMax) / 2
    medioY = (nodo.yMin + nodo.yMax) / 2
    x = puntoBuscar[0]
    y = puntoBuscar[1]

    if x < medioX and y >= medioY:
        return buscarVecino(nodo.hijos[0], puntoBuscar)
    if x >= medioX and y >= medioY:
        return buscarVecino(nodo.hijos[1], puntoBuscar)
    if x < medioX and y < medioY:
        return buscarVecino(nodo.hijos[2], puntoBuscar)
    if x >= medioX and y < medioY:
        return buscarVecino(nodo.hijos[3], puntoBuscar)

def puntoMasCercanoFuerzaBruta(direcciones, punto):
    mejorPunto = direcciones[0]
    mejorDistancia = calcularDistancia(direcciones[0], punto)

    for i in direcciones:
        dista = calcularDistancia(i, punto)
        if dista < mejorDistancia:
            mejorDistancia = dista
            mejorPunto = i

    return mejorPunto


tamanos = [100, 500, 1000, 5000, 10000]
tiemposArbol = []
tiemposBruta = []

for n in tamanos:
    direcciones = generar_direcciones(n)
    raiz = Nodo(0, 10000, 0, 10000)
    crearArbol(raiz, direcciones)

    puntoBuscar = (4500, 3200)

    inicio = time.time()
    puntoMasCercanoFuerzaBruta(direcciones, puntoBuscar)
    fin = time.time()
    tiempoBruta = fin - inicio

    inicio = time.time()
    buscarVecino(raiz, puntoBuscar)
    fin = time.time()
    tiempoArbol = fin - inicio

    tiemposBruta.append(tiempoBruta)
    tiemposArbol.append(tiempoArbol)
random.seed(8)
print("Tamaños:", tamanos)
print("Tiempos Quadtree:", [f"{t:.6f}" for t in tiemposArbol])
print("Tiempos Fuerza bruta:", [f"{t:.6f}" for t in tiemposBruta])

plt.figure(figsize=(8,5))
plt.plot(tamanos, tiemposArbol, marker='o', label="Quadtree")
plt.plot(tamanos, tiemposBruta, marker='o', label="Fuerza bruta")
plt.xlabel("Cantidad de puntos")
plt.ylabel("Tiempo (segundos)")
plt.title("Comparación de tiempos: Quadtree vs Fuerza bruta")
plt.legend()
plt.tight_layout()
plt.show()